config/routes.rb
Rails.application.routes.draw do
  get 'usage_profiles/new'

  root 'service_costs#index'

  resources :service_costs
  resources :service_usages, only: [:new]
  resources :usage_profiles

  get 'profiles/:id/plan-comparison' => 'profiles#plan_comparison', :as => :plan_comparison

end

app/models/plan.rb
# == Schema Information
#
# Table name: plans
#
#  id                :integer          not null, primary key
#  name              :string(150)
#  monthly_premium   :integer
#  annual_deductible :integer
#  max_oop           :integer
#  created_at        :datetime
#  updated_at        :datetime
#  coinsurance       :integer
#  code              :string(255)
#

class Plan < ActiveRecord::Base
  has_many :plan_benefits, :dependent => :destroy

  default_scope { order('sort_order ASC') }

  def annual_premium
    Calculator.calculate_annual_premium(self)
  end
end

app/models/plan_benefit.rb
# == Schema Information
#
# Table name: plan_benefits
#
#  id              :integer          not null, primary key
#  coinsurance     :boolean          default(FALSE)
#  copay           :integer          default(0)
#  plan_id         :integer
#  service_cost_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class PlanBenefit < ActiveRecord::Base
  belongs_to :plan
  belongs_to :service_cost
end

app/models/service_cost.rb
# == Schema Information
#
# Table name: service_costs
#
#  id         :integer          not null, primary key
#  name       :string(100)
#  cost       :integer
#  created_at :datetime
#  updated_at :datetime
#  order      :integer          default(0)
#

class ServiceCost < ActiveRecord::Base

  has_many :plan_benefits
  has_many :service_usages

  default_scope { order('service_costs.order ASC') }

end

app/models/service_usage.rb
# == Schema Information
#
# Table name: service_usages
#
#  id               :integer          not null, primary key
#  usage_count      :integer          default(1)
#  service_cost_id  :integer
#  usage_profile_id :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class ServiceUsage < ActiveRecord::Base
  belongs_to :service_cost
  belongs_to :usage_profile

  validates :usage_count, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0, :allow_blank => true }

  def benefit_for(plan)
    PlanBenefit.where(plan_id: plan.id, service_cost_id: service_cost.id).first
  end
end

app/models/usage_profile.rb
# == Schema Information
#
# Table name: usage_profiles
#
#  id            :integer          not null, primary key
#  zipcode       :string(10)
#  gender        :integer
#  date_of_birth :date
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class UsageProfile < ActiveRecord::Base
  belongs_to :user
  has_many :service_usages

  accepts_nested_attributes_for :service_usages, :allow_destroy => true

  enum gender: [:male, :female] unless instance_methods.include? :gender

  def cost_for_plan(plan)
    Calculator.calculate_for_usage_profile(self, plan)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  first      :string(100)
#  last       :string(100)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ActionController::Base

  def plan_comparison
    @profile = UsageProfile.find(params[:id])
    @plans = Plan.all
    gon.plans = @plans.to_a
    gon.premiums = @plans.map(&:annual_premium)
    gon.max_oops = {}
    gon.deductibles = {}

    gon.cost_totals = @plans.map do |plan|
      gon.max_oops[plan.name] = plan.max_oop
      gon.deductibles[plan.name] = plan.annual_deductible
      @profile.cost_for_plan(plan)
    end
    render layout: 'application'
  end
end

app/controllers/service_costs_controller.rb
class ServiceCostsController < ApplicationController
  def index
    @service_costs = ServiceCost.all
  end
end

app/controllers/service_usages_controller.rb
class ServiceUsagesController < ApplicationController
  def new
  end
end

app/controllers/usage_profiles_controller.rb
class UsageProfilesController < ApplicationController

  def new
    @usage_profile = UsageProfile.new
    ServiceCost.find_each do |sc|
      @usage_profile.service_usages.build(:service_cost => sc)
    end
  end

  def create
    @usage_profile = UsageProfile.new(usage_profile_params)
    if @usage_profile.save
      redirect_to plan_comparison_path(@usage_profile)
    else
      render :new
    end
  end

  def edit
    @usage_profile = UsageProfile.find(params[:id])
    render :new
  end

  def update
    @usage_profile = UsageProfile.find(params[:id])
    if @usage_profile.update_attributes(usage_profile_params)
      redirect_to plan_comparison_path(@usage_profile)
    else
      render :new
    end
  end

  private

  def usage_profile_params
    params.require(:usage_profile).permit(:id, :gender, :zipcode, :date_of_birth, service_usages_attributes: [ :id, :service_cost_id, :usage_count ])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_costs_helper.rb
module ServiceCostsHelper
end

app/helpers/usage_profiles_helper.rb
module UsageProfilesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HelpMeChoose
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = include_gon
    = csrf_meta_tags
    = content_for :head
  %body
    .container
      = yield

app/views/profiles/plan_comparison.html.haml
#container{style: "width:100%; height:400px;"}
  %p bididy bobidy BOO!
- content_for :head do
  = javascript_include_tag 'highcharts'
  = javascript_include_tag 'themes/gray'

%div.clear{style: "margin-top: 50px"}
  =link_to "< Edit Usage Profile", edit_usage_profile_path(@profile), :class => "button btn btn-success pull-left"


.row{style: "margin-top: 100px"}
  %h3 Description
  .row.well
    This page shows your expected healthcare cost breakdown per available plan.  Each plan has specified their annual deductible and maximum out-of-pocket costs.
    Total cost is comprised of the annual premium paid in addition to the sum of all the service costs accrued during the year.  The most cost-effective plan for
    you is the one with the <b>shortest</b> bar.
    %ul
      %li= "<font color='#BC5959'>Annual Premium</font>  - fixed cost for enrollement in a particular medical plan".html_safe
      %li=  "<font color='#94B8FF'>Service / Care</font>  - total paid by you for service and health care. Factors affecting this are the annual deductible and maximum out-of-pocket thresholds, service copays and co-insurance percentages.".html_safe

app/views/service_costs/index.html.haml
%h1.text-center Average cost of services for: 60614
.row
  .col-md-4.col-md-offset-4
    %table.table.table-striped.table-bordered
      %tr
        %th Service
        %th.text-right Typical Cost
      - @service_costs.each do |service|
        %tr
          %td=service.name
          %td.text-right=number_to_currency(service.cost)
    =link_to "Next", new_usage_profile_path, :class => "button btn btn-success pull-right"


%h3 Description
.row.well
  Typical Cost represents the actual reasonable amount a provider charges a customer in a region. Information such as this is becoming increasingly available thanks to services such as:
  %ul
    %li= link_to "ClearHealthCosts.com", "http://clearhealthcosts.com/"
    %li= link_to "Leslie's List", "http://leslieslist.org/"
    %li= link_to "Castlight Health", "http://www.castlighthealth.com/"

app/views/service_usages/new.html.haml
%h1.text-center Annual Usage Data
%p.text-center Enter in number of visits in past year for each category...

app/views/usage_profiles/new.html.haml
%h1.text-center Build a Usage Profile...
= simple_form_for @usage_profile, html: { class: "form-horizontal" } do |f|
  .row
    .col-md-4
      .form-group
        = f.label "Gender"
        = f.select :gender, [ ["Male", "male"],["Female", "female"] ], :html => { :class => "form-control" }
      .form-group
        = f.input :date_of_birth, :html => { :class => "form-control" }, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12, order: [:month, :day, :year]
      .form-group
        = f.input :zipcode, :html => { :class => "form-control" }
    .col-md-8
      = f.simple_fields_for :service_usages do |su|
        .form-group.pull-left{:style => "width: 150px; margin-right: 100px"}
          = su.label su.object.service_cost.name, su.object.service_cost.name
          = su.input_field :usage_count
          = su.hidden_field :service_cost_id
  .row
    .col-md-10
      = f.submit "Next", :class => "button btn btn-success pull-right"

%h3 Description
.row.well
  This page allows a consumer to specify their expected usage level for health services. This allows the system to calculate and predict which of the plans offered by their employer best suits their needs.